"""invitations and invite requests

The two tables behind `REGISTRATION_MODE=invite`: `invitation` is an allow-list keyed on the
address a member invited, and `invite_request` is the queue a stranger asks to be let in
through.

Nothing is backfilled and nothing existing is altered, which is the whole of why this is a
plain create. Registration was open before this revision, so there is no historical
invitation to reconstruct, and the accounts already in the table keep working - the gate
only ever asks about an address that has *no* account yet. `is_superuser` is likewise
untouched: the column has been on `user` since the baseline, and what changes above this
migration is only that something finally reads it.

Two column decisions worth reading beside the models. `invitation.email` is indexed and
deliberately **not** unique - two members may each invite the same friend, and each sees
their own row - while `invite_request.email` **is** unique, which is what makes the
anonymous endpoint's insert an `ON CONFLICT DO NOTHING` and its answer identical for a first
request and a repeat. And `invitation.user_id` is the *inviter* with `ondelete="CASCADE"`,
so an inviter's purge takes their invitations with it; an invitee's purge cannot reach them
down any key, which is why `_purge_one_account` deletes from both tables by address.

Revision ID: 0ef2c3c8954e
Revises: 52ac1982f461
Create Date: 2026-09-03 02:50:32.142906

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ef2c3c8954e"
down_revision: str | None = "52ac1982f461"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invite_request",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invite_request_created_at"), "invite_request", ["created_at"], unique=False)
    op.create_index(op.f("ix_invite_request_email"), "invite_request", ["email"], unique=True)
    op.create_table(
        "invitation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invitation_email"), "invitation", ["email"], unique=False)
    op.create_index(op.f("ix_invitation_user_id"), "invitation", ["user_id"], unique=False)
    op.create_index(op.f("ix_invitation_uuid"), "invitation", ["uuid"], unique=True)
    # ### end Alembic commands ###

    # Hand-added beside the generated block, in the `sa.literal_column` idiom the baseline
    # schema already uses for every other functional index here. `ix_user_email` is a plain
    # b-tree on the raw column and cannot serve a `lower(email)` predicate, which is what
    # every account comparison in the invitation path makes - so without this the batch
    # invite route runs up to a hundred sequential scans of `user` in one request.
    #
    # Not unique: accounts differing only in case can exist (`POST /auth/complete` inserts
    # the onboarding token's address verbatim), so a unique index here could fail to build
    # on a real instance and would assert a data shape this change did not establish.
    op.create_index("ix_user_email_lower", "user", [sa.literal_column("lower(email)")], unique=False)


def downgrade() -> None:
    # Mirrors the hand-added index above the generated block in `upgrade()`. The generated
    # half needs no help - dropping the two new tables takes their indexes with them - but
    # `ix_user_email_lower` sits on the pre-existing `user` table, so nothing else would ever
    # remove it: a downgrade would leave the prior revision's schema carrying an index it
    # does not declare, and the next `upgrade` would die on `already exists`. Every other
    # revision here that touches a pre-existing table reverses itself the same way.
    op.drop_index("ix_user_email_lower", table_name="user")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invitation_uuid"), table_name="invitation")
    op.drop_index(op.f("ix_invitation_user_id"), table_name="invitation")
    op.drop_index(op.f("ix_invitation_email"), table_name="invitation")
    op.drop_table("invitation")
    op.drop_index(op.f("ix_invite_request_email"), table_name="invite_request")
    op.drop_index(op.f("ix_invite_request_created_at"), table_name="invite_request")
    op.drop_table("invite_request")
    # ### end Alembic commands ###
