"""drop course.cost

`course.cost` was a free-text note ("EUR 650", "1 200 AUD including gear") on one entity, and
money is a cross-cutting concern the app has no architecture for - see *"`Course.cost` is gone,
and money is a cross-cutting concern this app has not designed yet"* in DECISIONS.md for the
reasoning and the alternatives.

**No data is preserved, deliberately.** Folding the stored strings into `course.notes` first was
considered and rejected: nothing is deployed anywhere, so the only rows this meets are local
development data. A self-hoster arriving later never had the column at all.

The `downgrade()` re-adds the column nullable and empty, which is the honest reversal - the
strings themselves are not recoverable from anything else on the row, and the column was nullable
throughout, so a database stepped back to `0ef2c3c8954e` is structurally identical to one that
never went forward.

Ordering worth knowing if this is ever re-cut: `CourseCreate` and `CourseUpdate` are
`extra="forbid"`, so the web client had to stop sending the key *before* this landed. It did
(opendiving-web, "courses no longer record a cost"). In the other order every course save 422s,
create and edit alike.

Revision ID: 84bee1255635
Revises: 0ef2c3c8954e
Create Date: 2026-09-03 23:17:30.388774

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84bee1255635"
down_revision: str | None = "0ef2c3c8954e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "cost")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("course", sa.Column("cost", sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
