"""server-side sessions and an auth audit trail

Two new tables, no backfill - and in both cases there is nothing an existing row *could* be
derived from rather than a backfill being skipped. Refresh tokens were stateless JWTs, so no
record of a live session exists anywhere to reconstruct one from; nothing has ever logged an
auth event, so there is no history to import. The tables start empty and fill from the next
sign-in.

**Existing refresh cookies stop working at their next rotation, and that is the breaking
change the PR title's `!` names.** A cookie minted before this carries no `sid` claim, and
`POST /auth/refresh` now requires one to resolve to a live `user_session` row. There is no
compatibility shim: everyone signed in is signed out once, which for a self-hoster is a
clean sign-out rather than corruption.

`ON DELETE CASCADE` on both `user_id` columns from the outset, so the account purge needs no
edit for `user_session` - but it *does* need one for `auth_audit_event`, whose pre-account
rows carry `user_id IS NULL` by design and which no cascade can therefore reach. That second
by-email arm is in `core/worker/functions.py::_purge_one_account`, beside the identical one
`authentication_request` already needed.

Revision ID: 8773a3c53fc9
Revises: 257c6ae0d5bb
Create Date: 2026-08-29 20:01:23.625934

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8773a3c53fc9"
down_revision: str | None = "257c6ae0d5bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_audit_event",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=False),
        sa.Column("user_agent", sa.String(length=400), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("provider", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_audit_event_created_at"), "auth_audit_event", ["created_at"], unique=False)
    op.create_index(op.f("ix_auth_audit_event_email"), "auth_audit_event", ["email"], unique=False)
    op.create_index(op.f("ix_auth_audit_event_event_type"), "auth_audit_event", ["event_type"], unique=False)
    op.create_index(op.f("ix_auth_audit_event_user_id"), "auth_audit_event", ["user_id"], unique=False)
    op.create_table(
        "user_session",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=False),
        sa.Column("user_agent", sa.String(length=400), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_session_expires_at"), "user_session", ["expires_at"], unique=False)
    op.create_index(op.f("ix_user_session_user_id"), "user_session", ["user_id"], unique=False)
    op.create_index(op.f("ix_user_session_uuid"), "user_session", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_session_uuid"), table_name="user_session")
    op.drop_index(op.f("ix_user_session_user_id"), table_name="user_session")
    op.drop_index(op.f("ix_user_session_expires_at"), table_name="user_session")
    op.drop_table("user_session")
    op.drop_index(op.f("ix_auth_audit_event_user_id"), table_name="auth_audit_event")
    op.drop_index(op.f("ix_auth_audit_event_event_type"), table_name="auth_audit_event")
    op.drop_index(op.f("ix_auth_audit_event_email"), table_name="auth_audit_event")
    op.drop_index(op.f("ix_auth_audit_event_created_at"), table_name="auth_audit_event")
    op.drop_table("auth_audit_event")
    # ### end Alembic commands ###
