"""add dive_mixture.usage

Revision ID: a400abb069ef
Revises: e417293f4502
Create Date: 2026-08-28 01:55:21.836095

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a400abb069ef"
down_revision: str | None = "e417293f4502"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dive_mixture", sa.Column("usage", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dive_mixture", "usage")
    # ### end Alembic commands ###
