"""baseline schema

The first revision, autogenerated against an empty database from the models as they stood
when migrations were introduced. Everything before it was applied by
`Base.metadata.create_all()` plus hand-run `ALTER TABLE`s (see `DECISIONS.md`), so there is
no earlier history to reconstruct - this revision *is* the history.

A database that predates it needs `alembic stamp a5a012820b2e` once, followed by
`alembic check`: the hand-run era is exactly where a machine can be missing a constraint or
carrying a dropped column, and a stamp asserts a state nobody verified. CONTRIBUTING.md
carries the full procedure.

Revision ID: a5a012820b2e
Revises:
Create Date: 2026-08-20 04:02:28.927772

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a5a012820b2e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "species",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("aphia_id", sa.Integer(), nullable=False),
        sa.Column("scientific_name", sa.String(length=255), nullable=False),
        sa.Column("rank", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("authority", sa.String(length=255), nullable=True),
        sa.Column("kingdom", sa.String(length=255), nullable=True),
        sa.Column("phylum", sa.String(length=255), nullable=True),
        sa.Column("class_name", sa.String(length=255), nullable=True),
        sa.Column("order_name", sa.String(length=255), nullable=True),
        sa.Column("family", sa.String(length=255), nullable=True),
        sa.Column("genus", sa.String(length=255), nullable=True),
        sa.Column("is_marine", sa.Boolean(), nullable=True),
        sa.Column("is_brackish", sa.Boolean(), nullable=True),
        sa.Column("is_freshwater", sa.Boolean(), nullable=True),
        sa.Column("common_name", sa.String(length=255), nullable=True),
        sa.Column("wikidata_qid", sa.String(length=32), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_species_aphia_id"), "species", ["aphia_id"], unique=True)
    op.create_index(op.f("ix_species_uuid"), "species", ["uuid"], unique=True)
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_token_blacklist_expires_at"), "token_blacklist", ["expires_at"], unique=False)
    op.create_index(op.f("ix_token_blacklist_token"), "token_blacklist", ["token"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("profile_image_url", sa.String(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("gear_service_emails", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("units", sa.String(length=16), server_default="metric", nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_is_deleted"), "user", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_index(op.f("ix_user_uuid"), "user", ["uuid"], unique=True)
    op.create_table(
        "authentication_provider",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_user_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_user_id", name="uq_authentication_provider_provider_identity"),
        sa.UniqueConstraint("user_id", "provider", name="uq_authentication_provider_user_provider"),
    )
    op.create_index(
        op.f("ix_authentication_provider_provider_user_id"),
        "authentication_provider",
        ["provider_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_authentication_provider_user_id"), "authentication_provider", ["user_id"], unique=False)
    op.create_table(
        "authentication_request",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purpose", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_authentication_request_email"), "authentication_request", ["email"], unique=False)
    op.create_index(op.f("ix_authentication_request_token_hash"), "authentication_request", ["token_hash"], unique=True)
    op.create_index(op.f("ix_authentication_request_user_id"), "authentication_request", ["user_id"], unique=False)
    op.create_table(
        "certification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("agency", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("agency_other", sa.String(length=64), nullable=True),
        sa.Column("certification_number", sa.String(length=64), nullable=True),
        sa.Column("certified_on", sa.Date(), nullable=True),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("instructor_name", sa.String(length=255), nullable=True),
        sa.Column("instructor_number", sa.String(length=64), nullable=True),
        sa.Column("training_center", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_certification_user_id"), "certification", ["user_id"], unique=False)
    op.create_index(
        "ix_certification_user_id_certified_on",
        "certification",
        ["user_id", sa.literal_column("certified_on DESC NULLS LAST")],
        unique=False,
        postgresql_where=sa.text("is_deleted IS false"),
    )
    op.create_index(op.f("ix_certification_uuid"), "certification", ["uuid"], unique=True)
    op.create_table(
        "dive_site",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dive_site_user_id"), "dive_site", ["user_id"], unique=False)
    op.create_index("ix_dive_site_user_id_name", "dive_site", ["user_id", "name"], unique=False)
    op.create_index(op.f("ix_dive_site_uuid"), "dive_site", ["uuid"], unique=True)
    op.create_index(
        "ux_dive_site_user_id_name_location_lower",
        "dive_site",
        ["user_id", sa.literal_column("lower(name)"), sa.literal_column("coalesce(lower(location), '')")],
        unique=True,
    )
    op.create_table(
        "gear_item",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("brand", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("rented", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dive_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gear_item_user_id"), "gear_item", ["user_id"], unique=False)
    op.create_index("ix_gear_item_user_id_name", "gear_item", ["user_id", "name"], unique=False)
    op.create_index(op.f("ix_gear_item_uuid"), "gear_item", ["uuid"], unique=True)
    op.create_index(
        "ux_gear_item_user_id_brand_name_lower",
        "gear_item",
        ["user_id", sa.literal_column("coalesce(lower(brand), '')"), sa.literal_column("lower(name)")],
        unique=True,
    )
    op.create_table(
        "gear_set",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gear_set_user_id"), "gear_set", ["user_id"], unique=False)
    op.create_index("ix_gear_set_user_id_name", "gear_set", ["user_id", "name"], unique=False)
    op.create_index(op.f("ix_gear_set_uuid"), "gear_set", ["uuid"], unique=True)
    op.create_index(
        "ux_gear_set_user_id_name_lower", "gear_set", ["user_id", sa.literal_column("lower(name)")], unique=True
    )
    op.create_table(
        "species_name",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("species_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("language_code", sa.String(length=3), nullable=True),
        sa.ForeignKeyConstraint(["species_id"], ["species.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("species_id", "name", "kind", name="ux_species_name_species_id_name_kind"),
    )
    op.create_index(op.f("ix_species_name_species_id"), "species_name", ["species_id"], unique=False)
    op.create_table(
        "trip",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trip_user_id"), "trip", ["user_id"], unique=False)
    op.create_index(
        "ix_trip_user_id_start_date", "trip", ["user_id", sa.literal_column("start_date DESC")], unique=False
    )
    op.create_index(op.f("ix_trip_uuid"), "trip", ["uuid"], unique=True)
    op.create_index("ux_trip_user_id_name_lower", "trip", ["user_id", sa.literal_column("lower(name)")], unique=True)
    op.create_table(
        "user_dive_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("total_dives", sa.Integer(), nullable=False),
        sa.Column("max_depth", sa.Float(), nullable=False),
        sa.Column("total_time", sa.Integer(), nullable=False),
        sa.Column("species_seen", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_dive_stats_user_id"), "user_dive_stats", ["user_id"], unique=True)
    op.create_table(
        "certification_file",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("certification_id", sa.Integer(), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["certification_id"], ["certification.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_certification_file_certification_id"), "certification_file", ["certification_id"], unique=False
    )
    op.create_index(op.f("ix_certification_file_uuid"), "certification_file", ["uuid"], unique=True)
    op.create_index(
        "ux_certification_file_certification_id_side", "certification_file", ["certification_id", "side"], unique=True
    )
    op.create_table(
        "dive",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("dive_number", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("utc_offset_minutes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_depth", sa.Float(), nullable=True),
        sa.Column("avg_depth", sa.Float(), nullable=True),
        sa.Column("bottom_temperature", sa.Float(), nullable=True),
        sa.Column("visibility", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("water_type", sa.String(length=32), nullable=True),
        sa.Column("altitude", sa.Integer(), nullable=True),
        sa.Column("trip_id", sa.Integer(), nullable=True),
        sa.Column("cns_start", sa.Float(), nullable=True),
        sa.Column("cns_end", sa.Float(), nullable=True),
        sa.Column("otu_start", sa.Float(), nullable=True),
        sa.Column("otu_end", sa.Float(), nullable=True),
        sa.Column("surface_pressure_bar", sa.Float(), nullable=True),
        sa.Column("entry_latitude", sa.Float(), nullable=True),
        sa.Column("entry_longitude", sa.Float(), nullable=True),
        sa.Column("exit_latitude", sa.Float(), nullable=True),
        sa.Column("exit_longitude", sa.Float(), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.CheckConstraint("(entry_latitude IS NULL) = (entry_longitude IS NULL)", name="ck_dive_entry_position_pair"),
        sa.CheckConstraint("(exit_latitude IS NULL) = (exit_longitude IS NULL)", name="ck_dive_exit_position_pair"),
        sa.CheckConstraint(
            "altitude IS NULL OR (altitude >= -450 AND altitude <= 6500)", name="ck_dive_altitude_range"
        ),
        sa.CheckConstraint("avg_depth IS NULL OR avg_depth > 0", name="ck_dive_avg_depth_positive"),
        sa.CheckConstraint("cns_end IS NULL OR cns_end >= 0", name="ck_dive_cns_end_non_negative"),
        sa.CheckConstraint("cns_start IS NULL OR cns_start >= 0", name="ck_dive_cns_start_non_negative"),
        sa.CheckConstraint("duration > 0", name="ck_dive_duration_positive"),
        sa.CheckConstraint(
            "entry_latitude IS NULL OR (entry_latitude >= -90 AND entry_latitude <= 90)",
            name="ck_dive_entry_latitude_range",
        ),
        sa.CheckConstraint(
            "entry_longitude IS NULL OR (entry_longitude >= -180 AND entry_longitude <= 180)",
            name="ck_dive_entry_longitude_range",
        ),
        sa.CheckConstraint(
            "exit_latitude IS NULL OR (exit_latitude >= -90 AND exit_latitude <= 90)",
            name="ck_dive_exit_latitude_range",
        ),
        sa.CheckConstraint(
            "exit_longitude IS NULL OR (exit_longitude >= -180 AND exit_longitude <= 180)",
            name="ck_dive_exit_longitude_range",
        ),
        sa.CheckConstraint("max_depth IS NULL OR max_depth > 0", name="ck_dive_max_depth_positive"),
        sa.CheckConstraint("otu_end IS NULL OR otu_end >= 0", name="ck_dive_otu_end_non_negative"),
        sa.CheckConstraint("otu_start IS NULL OR otu_start >= 0", name="ck_dive_otu_start_non_negative"),
        sa.CheckConstraint(
            "surface_pressure_bar IS NULL OR (surface_pressure_bar >= 0.5 AND surface_pressure_bar <= 1.2)",
            name="ck_dive_surface_pressure_range",
        ),
        sa.CheckConstraint("visibility IS NULL OR visibility >= 0", name="ck_dive_visibility_non_negative"),
        sa.CheckConstraint("weight IS NULL OR weight >= 0", name="ck_dive_weight_non_negative"),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dive_trip_id"), "dive", ["trip_id"], unique=False)
    op.create_index(op.f("ix_dive_user_id"), "dive", ["user_id"], unique=False)
    op.create_index(
        "ix_dive_user_id_start_time",
        "dive",
        ["user_id", sa.literal_column("start_time DESC")],
        unique=False,
        postgresql_where=sa.text("is_deleted IS false"),
    )
    op.create_index(
        "ix_dive_user_id_stats",
        "dive",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("is_deleted IS false"),
        postgresql_include=["max_depth", "duration"],
    )
    op.create_index(op.f("ix_dive_uuid"), "dive", ["uuid"], unique=True)
    op.create_table(
        "gear_service_schedule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("gear_item_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("interval_months", sa.Integer(), nullable=True),
        sa.Column("interval_dives", sa.Integer(), nullable=True),
        sa.Column("dive_count_at_start", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_service_on", sa.Date(), nullable=True),
        sa.Column("next_due_on", sa.Date(), nullable=True),
        sa.Column("next_due_at_dive_count", sa.Integer(), nullable=True),
        sa.Column("notified_stage", sa.String(length=16), nullable=True),
        sa.Column("notified_for_due_on", sa.Date(), nullable=True),
        sa.Column("notified_for_due_at_dive_count", sa.Integer(), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "interval_dives IS NULL OR interval_dives > 0", name="ck_gear_service_schedule_interval_dives_positive"
        ),
        sa.CheckConstraint(
            "interval_months IS NOT NULL OR interval_dives IS NOT NULL", name="ck_gear_service_schedule_has_an_interval"
        ),
        sa.CheckConstraint(
            "interval_months IS NULL OR interval_months > 0", name="ck_gear_service_schedule_interval_months_positive"
        ),
        sa.ForeignKeyConstraint(["gear_item_id"], ["gear_item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_gear_service_schedule_next_due_on",
        "gear_service_schedule",
        ["next_due_on"],
        unique=False,
        postgresql_where=sa.text("is_active IS true"),
    )
    op.create_index(op.f("ix_gear_service_schedule_user_id"), "gear_service_schedule", ["user_id"], unique=False)
    op.create_index(op.f("ix_gear_service_schedule_uuid"), "gear_service_schedule", ["uuid"], unique=True)
    op.create_index(
        "ux_gear_service_schedule_item_kind_label",
        "gear_service_schedule",
        ["gear_item_id", "kind", sa.literal_column("coalesce(lower(label), '')")],
        unique=True,
    )
    op.create_table(
        "gear_set_item",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gear_set_id", sa.Integer(), nullable=False),
        sa.Column("gear_item_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["gear_item_id"], ["gear_item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["gear_set_id"], ["gear_set.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gear_set_id", "gear_item_id", name="ux_gear_set_item_gear_set_id_gear_item_id"),
    )
    op.create_index(op.f("ix_gear_set_item_gear_item_id"), "gear_set_item", ["gear_item_id"], unique=False)
    op.create_index("ix_gear_set_item_gear_set_id_position", "gear_set_item", ["gear_set_id", "position"], unique=False)
    op.create_table(
        "trip_location",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=512), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("bbox_south", sa.Float(), nullable=True),
        sa.Column("bbox_north", sa.Float(), nullable=True),
        sa.Column("bbox_west", sa.Float(), nullable=True),
        sa.Column("bbox_east", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_trip_location_trip_id_position", "trip_location", ["trip_id", "position"], unique=False)
    op.create_table(
        "dive_dive_site",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dive_id", sa.Integer(), nullable=False),
        sa.Column("dive_site_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dive_id"], ["dive.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["dive_site_id"], ["dive_site.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dive_id", "dive_site_id", name="ux_dive_dive_site_dive_id_dive_site_id"),
    )
    op.create_index("ix_dive_dive_site_dive_id_position", "dive_dive_site", ["dive_id", "position"], unique=False)
    op.create_index(op.f("ix_dive_dive_site_dive_site_id"), "dive_dive_site", ["dive_site_id"], unique=False)
    op.create_table(
        "dive_file",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("dive_id", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("parser_key", sa.String(length=32), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dive_id"], ["dive.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dive_file_uuid"), "dive_file", ["uuid"], unique=True)
    op.create_index("ux_dive_file_dive_id", "dive_file", ["dive_id"], unique=True)
    op.create_index("ux_dive_file_user_id_sha256", "dive_file", ["user_id", "sha256"], unique=True)
    op.create_table(
        "dive_gear_item",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dive_id", sa.Integer(), nullable=False),
        sa.Column("gear_item_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dive_id"], ["dive.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["gear_item_id"], ["gear_item.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dive_id", "gear_item_id", name="ux_dive_gear_item_dive_id_gear_item_id"),
    )
    op.create_index("ix_dive_gear_item_dive_id_position", "dive_gear_item", ["dive_id", "position"], unique=False)
    op.create_index(op.f("ix_dive_gear_item_gear_item_id"), "dive_gear_item", ["gear_item_id"], unique=False)
    op.create_table(
        "dive_mixture",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dive_id", sa.Integer(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("start_pressure", sa.Float(), nullable=True),
        sa.Column("end_pressure", sa.Float(), nullable=True),
        sa.Column("oxygen", sa.Float(), nullable=False),
        sa.Column("helium", sa.Float(), nullable=False),
        sa.Column("po2_limit", sa.Float(), nullable=True),
        sa.Column("gas_number", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=True),
        sa.CheckConstraint(
            "end_pressure IS NULL OR (end_pressure >= 0 AND end_pressure <= 350)",
            name="ck_dive_mixture_end_pressure_range",
        ),
        sa.CheckConstraint("gas_number IS NULL OR gas_number >= 0", name="ck_dive_mixture_gas_number_non_negative"),
        sa.CheckConstraint("helium >= 0 AND helium <= 100", name="ck_dive_mixture_helium_range"),
        sa.CheckConstraint("oxygen + helium <= 100", name="ck_dive_mixture_oxygen_helium_sum"),
        sa.CheckConstraint("oxygen >= 0 AND oxygen <= 100", name="ck_dive_mixture_oxygen_range"),
        sa.CheckConstraint(
            "po2_limit IS NULL OR (po2_limit >= 0.4 AND po2_limit <= 2.0)", name="ck_dive_mixture_po2_limit_range"
        ),
        sa.CheckConstraint(
            "start_pressure IS NULL OR (start_pressure > 0 AND start_pressure <= 350)",
            name="ck_dive_mixture_start_pressure_range",
        ),
        sa.CheckConstraint(
            "start_pressure IS NULL OR end_pressure IS NULL OR end_pressure <= start_pressure",
            name="ck_dive_mixture_pressure_order",
        ),
        sa.CheckConstraint("volume > 0", name="ck_dive_mixture_volume_positive"),
        sa.ForeignKeyConstraint(["dive_id"], ["dive.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dive_mixture_dive_id"), "dive_mixture", ["dive_id"], unique=False)
    op.create_table(
        "dive_profile",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dive_id", sa.Integer(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("parser_key", sa.String(length=32), nullable=False),
        sa.Column("extractor_version", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("depth_sample_count", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_depth_cm", sa.Integer(), nullable=True),
        sa.Column("max_ceiling_cm", sa.Integer(), nullable=True),
        sa.Column("min_temperature_c10", sa.Integer(), nullable=True),
        sa.Column("max_temperature_c10", sa.Integer(), nullable=True),
        sa.Column("min_pressure_bar10", sa.Integer(), nullable=True),
        sa.Column("max_pressure_bar10", sa.Integer(), nullable=True),
        sa.Column("event_count", sa.Integer(), nullable=True),
        sa.Column("gas_attribution", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dive_id"], ["dive.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dive_profile_uuid"), "dive_profile", ["uuid"], unique=True)
    op.create_index("ux_dive_profile_dive_id", "dive_profile", ["dive_id"], unique=True)
    op.create_table(
        "dive_species",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dive_id", sa.Integer(), nullable=False),
        sa.Column("species_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dive_id"], ["dive.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["species_id"], ["species.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dive_id", "species_id", name="ux_dive_species_dive_id_species_id"),
    )
    op.create_index("ix_dive_species_dive_id_position", "dive_species", ["dive_id", "position"], unique=False)
    op.create_index(op.f("ix_dive_species_species_id"), "dive_species", ["species_id"], unique=False)
    op.create_table(
        "gear_service_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("gear_item_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("serviced_on", sa.Date(), nullable=False),
        sa.Column("dive_count_at_service", sa.Integer(), nullable=False),
        sa.Column("gear_service_schedule_id", sa.Integer(), nullable=True),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("performed_by", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["gear_item_id"], ["gear_item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["gear_service_schedule_id"], ["gear_service_schedule.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_gear_service_record_gear_item_id", "gear_service_record", ["gear_item_id"], unique=False)
    op.create_index(
        "ix_gear_service_record_gear_item_id_serviced_on",
        "gear_service_record",
        ["gear_item_id", sa.literal_column("serviced_on DESC")],
        unique=False,
        postgresql_where=sa.text("is_deleted IS false"),
    )
    op.create_index(
        "ix_gear_service_record_schedule_id", "gear_service_record", ["gear_service_schedule_id"], unique=False
    )
    op.create_index(
        "ix_gear_service_record_schedule_id_serviced_on",
        "gear_service_record",
        ["gear_service_schedule_id", sa.literal_column("serviced_on DESC")],
        unique=False,
        postgresql_where=sa.text("is_deleted IS false"),
    )
    op.create_index(op.f("ix_gear_service_record_user_id"), "gear_service_record", ["user_id"], unique=False)
    op.create_index(op.f("ix_gear_service_record_uuid"), "gear_service_record", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gear_service_record_uuid"), table_name="gear_service_record")
    op.drop_index(op.f("ix_gear_service_record_user_id"), table_name="gear_service_record")
    op.drop_index(
        "ix_gear_service_record_schedule_id_serviced_on",
        table_name="gear_service_record",
        postgresql_where=sa.text("is_deleted IS false"),
    )
    op.drop_index("ix_gear_service_record_schedule_id", table_name="gear_service_record")
    op.drop_index(
        "ix_gear_service_record_gear_item_id_serviced_on",
        table_name="gear_service_record",
        postgresql_where=sa.text("is_deleted IS false"),
    )
    op.drop_index("ix_gear_service_record_gear_item_id", table_name="gear_service_record")
    op.drop_table("gear_service_record")
    op.drop_index(op.f("ix_dive_species_species_id"), table_name="dive_species")
    op.drop_index("ix_dive_species_dive_id_position", table_name="dive_species")
    op.drop_table("dive_species")
    op.drop_index("ux_dive_profile_dive_id", table_name="dive_profile")
    op.drop_index(op.f("ix_dive_profile_uuid"), table_name="dive_profile")
    op.drop_table("dive_profile")
    op.drop_index(op.f("ix_dive_mixture_dive_id"), table_name="dive_mixture")
    op.drop_table("dive_mixture")
    op.drop_index(op.f("ix_dive_gear_item_gear_item_id"), table_name="dive_gear_item")
    op.drop_index("ix_dive_gear_item_dive_id_position", table_name="dive_gear_item")
    op.drop_table("dive_gear_item")
    op.drop_index("ux_dive_file_user_id_sha256", table_name="dive_file")
    op.drop_index("ux_dive_file_dive_id", table_name="dive_file")
    op.drop_index(op.f("ix_dive_file_uuid"), table_name="dive_file")
    op.drop_table("dive_file")
    op.drop_index(op.f("ix_dive_dive_site_dive_site_id"), table_name="dive_dive_site")
    op.drop_index("ix_dive_dive_site_dive_id_position", table_name="dive_dive_site")
    op.drop_table("dive_dive_site")
    op.drop_index("ix_trip_location_trip_id_position", table_name="trip_location")
    op.drop_table("trip_location")
    op.drop_index("ix_gear_set_item_gear_set_id_position", table_name="gear_set_item")
    op.drop_index(op.f("ix_gear_set_item_gear_item_id"), table_name="gear_set_item")
    op.drop_table("gear_set_item")
    op.drop_index("ux_gear_service_schedule_item_kind_label", table_name="gear_service_schedule")
    op.drop_index(op.f("ix_gear_service_schedule_uuid"), table_name="gear_service_schedule")
    op.drop_index(op.f("ix_gear_service_schedule_user_id"), table_name="gear_service_schedule")
    op.drop_index(
        "ix_gear_service_schedule_next_due_on",
        table_name="gear_service_schedule",
        postgresql_where=sa.text("is_active IS true"),
    )
    op.drop_table("gear_service_schedule")
    op.drop_index(op.f("ix_dive_uuid"), table_name="dive")
    op.drop_index(
        "ix_dive_user_id_stats",
        table_name="dive",
        postgresql_where=sa.text("is_deleted IS false"),
        postgresql_include=["max_depth", "duration"],
    )
    op.drop_index("ix_dive_user_id_start_time", table_name="dive", postgresql_where=sa.text("is_deleted IS false"))
    op.drop_index(op.f("ix_dive_user_id"), table_name="dive")
    op.drop_index(op.f("ix_dive_trip_id"), table_name="dive")
    op.drop_table("dive")
    op.drop_index("ux_certification_file_certification_id_side", table_name="certification_file")
    op.drop_index(op.f("ix_certification_file_uuid"), table_name="certification_file")
    op.drop_index(op.f("ix_certification_file_certification_id"), table_name="certification_file")
    op.drop_table("certification_file")
    op.drop_index(op.f("ix_user_dive_stats_user_id"), table_name="user_dive_stats")
    op.drop_table("user_dive_stats")
    op.drop_index("ux_trip_user_id_name_lower", table_name="trip")
    op.drop_index(op.f("ix_trip_uuid"), table_name="trip")
    op.drop_index("ix_trip_user_id_start_date", table_name="trip")
    op.drop_index(op.f("ix_trip_user_id"), table_name="trip")
    op.drop_table("trip")
    op.drop_index(op.f("ix_species_name_species_id"), table_name="species_name")
    op.drop_table("species_name")
    op.drop_index("ux_gear_set_user_id_name_lower", table_name="gear_set")
    op.drop_index(op.f("ix_gear_set_uuid"), table_name="gear_set")
    op.drop_index("ix_gear_set_user_id_name", table_name="gear_set")
    op.drop_index(op.f("ix_gear_set_user_id"), table_name="gear_set")
    op.drop_table("gear_set")
    op.drop_index("ux_gear_item_user_id_brand_name_lower", table_name="gear_item")
    op.drop_index(op.f("ix_gear_item_uuid"), table_name="gear_item")
    op.drop_index("ix_gear_item_user_id_name", table_name="gear_item")
    op.drop_index(op.f("ix_gear_item_user_id"), table_name="gear_item")
    op.drop_table("gear_item")
    op.drop_index("ux_dive_site_user_id_name_location_lower", table_name="dive_site")
    op.drop_index(op.f("ix_dive_site_uuid"), table_name="dive_site")
    op.drop_index("ix_dive_site_user_id_name", table_name="dive_site")
    op.drop_index(op.f("ix_dive_site_user_id"), table_name="dive_site")
    op.drop_table("dive_site")
    op.drop_index(op.f("ix_certification_uuid"), table_name="certification")
    op.drop_index(
        "ix_certification_user_id_certified_on",
        table_name="certification",
        postgresql_where=sa.text("is_deleted IS false"),
    )
    op.drop_index(op.f("ix_certification_user_id"), table_name="certification")
    op.drop_table("certification")
    op.drop_index(op.f("ix_authentication_request_user_id"), table_name="authentication_request")
    op.drop_index(op.f("ix_authentication_request_token_hash"), table_name="authentication_request")
    op.drop_index(op.f("ix_authentication_request_email"), table_name="authentication_request")
    op.drop_table("authentication_request")
    op.drop_index(op.f("ix_authentication_provider_user_id"), table_name="authentication_provider")
    op.drop_index(op.f("ix_authentication_provider_provider_user_id"), table_name="authentication_provider")
    op.drop_table("authentication_provider")
    op.drop_index(op.f("ix_user_uuid"), table_name="user")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_is_deleted"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_token_blacklist_token"), table_name="token_blacklist")
    op.drop_index(op.f("ix_token_blacklist_expires_at"), table_name="token_blacklist")
    op.drop_table("token_blacklist")
    op.drop_index(op.f("ix_species_uuid"), table_name="species")
    op.drop_index(op.f("ix_species_aphia_id"), table_name="species")
    op.drop_table("species")
    # ### end Alembic commands ###
