"""map pictures, drawn on first view

Revision ID: b4fa9c171ebb
Revises: 14395821e42b
Create Date: 2026-10-01 09:04:38.142441

One new table and nothing to backfill: a dive's or trip's map picture is drawn the first
time its card asks for it, so existing records get theirs as they are viewed. `user_id` is
`ON DELETE CASCADE` from the outset, and the account purge reads the rows' keys before its
`DELETE`.

`downgrade()` drops the table; the files it named are then orphans the sweeper reclaims.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4fa9c171ebb"
down_revision: str | None = "14395821e42b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "map_picture",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("theme", sa.String(length=8), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_served_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("theme IN ('light', 'dark')", name="ck_map_picture_theme"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_map_picture_last_served_at", "map_picture", ["last_served_at"], unique=False)
    op.create_index("ux_map_picture_storage_key", "map_picture", ["storage_key"], unique=True)
    op.create_index("ux_map_picture_user_id_digest_theme", "map_picture", ["user_id", "digest", "theme"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ux_map_picture_user_id_digest_theme", table_name="map_picture")
    op.drop_index("ux_map_picture_storage_key", table_name="map_picture")
    op.drop_index("ix_map_picture_last_served_at", table_name="map_picture")
    op.drop_table("map_picture")
    # ### end Alembic commands ###
