"""record when a token was revoked

`token_blacklist.expires_at` is copied from the token's own `exp`, so it says when the
token was *issued*, never when it was revoked. That leaves the one question worth asking
about a revoked refresh token being presented again unanswerable: how long after it was
spent did the replay arrive? Milliseconds is rotation's documented two-tab race; minutes
or hours is a stolen cookie. `api.v1.auth._warn_if_revoked` is the only reader.

Existing rows are backfilled to the moment the migration runs, which is later than they
were actually revoked. That is fine and not worth a smarter `USING`: the table only holds
entries until the token they name would have expired anyway, and the first
`purge_expired_tokens` run after this clears them out.

Revision ID: e30bd5792bbe
Revises: a5a012820b2e
Create Date: 2026-08-20 17:29:59.183340

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e30bd5792bbe"
down_revision: str | None = "a5a012820b2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "token_blacklist",
        sa.Column("revoked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("token_blacklist", "revoked_at")
    # ### end Alembic commands ###
