"""add webauthn_credential for passkeys

One new table, no backfill: passkeys are registered from scratch, so there is nothing an
existing row could be derived from. `authentication_provider` could not host them - its
`(user_id, provider)` unique constraint allows one row per provider, and passkeys are
many-per-user with per-credential state (public key, signature counter, transports) that
has no column there.

`ON DELETE CASCADE` on `user_id` from the outset, so `plans/account-deletion.md`'s purge
needs no edit for this table: a credential that outlived its account would still be a live
sign-in path.

Revision ID: f7710514ddde
Revises: 60ec1a2894ea
Create Date: 2026-08-20 22:31:10.412262

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7710514ddde"
down_revision: str | None = "60ec1a2894ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webauthn_credential",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.LargeBinary(), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("sign_count", sa.BigInteger(), nullable=False),
        sa.Column("transports", sa.JSON(), nullable=True),
        sa.Column("aaguid", sa.Uuid(), nullable=True),
        sa.Column("backed_up", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webauthn_credential_credential_id"), "webauthn_credential", ["credential_id"], unique=True)
    op.create_index(op.f("ix_webauthn_credential_user_id"), "webauthn_credential", ["user_id"], unique=False)
    op.create_index(op.f("ix_webauthn_credential_uuid"), "webauthn_credential", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webauthn_credential_uuid"), table_name="webauthn_credential")
    op.drop_index(op.f("ix_webauthn_credential_user_id"), table_name="webauthn_credential")
    op.drop_index(op.f("ix_webauthn_credential_credential_id"), table_name="webauthn_credential")
    op.drop_table("webauthn_credential")
    # ### end Alembic commands ###
