"""Name the water at a position, from polygons vendored in the repo.

Mostly seas and oceans, hence the module name, but the dataset also carries gulfs, straits,
fjords, a few estuarine rivers and two reefs - see `water_name`.

This exists because a pin in genuinely open water reverse-geocodes to nothing. Nominatim
does not consult sea polygons on `/reverse` at all - `27.0, 35.0` in the Red Sea and
`30.0, -40.0` in the mid-Atlantic both answer `{"error": "Unable to geocode"}`, at every
zoom level and with `layer=natural` - and open water is where a great deal of diving
happens. `services.geocoding_service` calls this only when the provider had nothing.

**Why a data file rather than a second provider.** Marine Regions' REST API answers the same
question, but adding it would mean a second outbound host, a second licence and a second
failure mode for a feature whose whole selling point is that it works out of the box. The
data is small, public domain, and does not change: 293 Natural Earth polygons, checked in.
That also matches what this project decided when it kept dive-site coordinates in two plain
`Float` columns rather than adding PostGIS - a self-hoster should not acquire an install
step for a coarse convenience.

**Why no geometry library.** Ray casting over 324 polygon parts, behind a bounding-box
reject, is a few dozen lines. `shapely` would pull GEOS into the image to do the same
arithmetic. Measured over a 10,680-point global grid, which exercises the branch that cannot
return early - a land point, where every part is bounding-box tested - the worst lookup is
0.26 ms and the median 0.06 ms.

`data/marine_areas.geojson` is regenerated by `scripts/build_marine_areas.py`, which records
the source URL, the retrieval date and the licence inside the file itself.
"""

import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "marine_areas.geojson"

Ring = tuple[tuple[float, float], ...]


@dataclass(frozen=True, slots=True)
class _Part:
    """One contiguous polygon, not one sea.

    Splitting per part rather than per feature is what keeps the antimeridian out of this
    module: the Bering Sea arrives from Natural Earth as two polygons, one either side of
    ±180, so each one is an ordinary lon/lat rectangle. It also sharpens the bounding box -
    a feature-level box for the Bering would span the entire globe and reject nothing.
    """

    name: str
    min_lon: float
    min_lat: float
    max_lon: float
    max_lat: float
    # Outer ring first, holes after. The holes are islands, and a diver standing on one is
    # not in the sea.
    rings: tuple[Ring, ...]

    @property
    def box_area(self) -> float:
        return (self.max_lon - self.min_lon) * (self.max_lat - self.min_lat)


# Set by `_parts` on the first successful read, and only then - see its docstring.
_loaded: tuple[_Part, ...] | None = None

# Whether a failed read has already been reported at WARNING - see `_load`.
_warned = False


def _ring(coordinates: list[Any]) -> Ring:
    return tuple((float(point[0]), float(point[1])) for point in coordinates)


def _parts_of(name: str, geometry: dict[str, Any]) -> list[_Part]:
    polygons = [geometry["coordinates"]] if geometry["type"] == "Polygon" else geometry["coordinates"]

    parts: list[_Part] = []
    for polygon in polygons:
        # Empty rings are dropped here rather than guarded against in `_ring_contains`: a
        # ringless hole is meaningless, and the alternative is a file that loads cleanly and
        # then raises at lookup time - the one shape of failure this module promises not to
        # have. `_geometry` in the generator cannot emit one, but a hand-edited or foreign
        # file can, which is what the rest of `_load`'s defensiveness is for. An empty
        # *outer* ring still fails the load, via `min()` below.
        rings = tuple(ring for ring in (_ring(ring) for ring in polygon) if ring)
        longitudes = [longitude for longitude, _ in rings[0]]
        latitudes = [latitude for _, latitude in rings[0]]
        parts.append(
            _Part(
                name=name,
                min_lon=min(longitudes),
                min_lat=min(latitudes),
                max_lon=max(longitudes),
                max_lat=max(latitudes),
                rings=rings,
            )
        )
    return parts


def _load() -> tuple[_Part, ...] | None:
    """Every polygon part, **smallest bounding box first**, so the first hit wins - or `None`
    if the file could not be read.

    Reading it is the only step in this module that touches the world, and
    `services.geocoding_service` promises the whole path degrades to "no suggestion" rather
    than raising: a 500 from a truncated data file would break the dive-site form over a
    convenience.

    Overlap is the norm rather than the exception in this dataset - a point in the Red Sea
    is also inside "Indian Ocean", and one in the Coral Sea is inside "South Pacific Ocean".
    The smaller polygon is always the more useful answer to "where is this dive", so sorting
    once at load turns "smallest match wins" into "return on the first match" and removes the
    need to test the rest.

    Comparing *bounding box* area rather than true polygon area is deliberate: it needs no
    geometry library and is not a close call for any pair this has to separate.
    """
    try:
        document = json.loads(_DATA_PATH.read_text(encoding="utf-8"))
        parts = [
            part
            for feature in document["features"]
            for part in _parts_of(feature["properties"]["name"], feature["geometry"])
        ]
    except (OSError, ValueError, TypeError, KeyError, IndexError) as exc:
        # Loud once, then quiet. `_parts` retries on every lookup, so a genuinely broken
        # deploy would otherwise write this line for every offshore pin for as long as it
        # stayed broken - and `core.logger` writes to a file on disk.
        global _warned
        logger.log(
            logging.DEBUG if _warned else logging.WARNING,
            "Could not read %s (%s); offshore positions will go unnamed.",
            _DATA_PATH.name,
            exc,
        )
        _warned = True
        return None

    parts.sort(key=lambda part: part.box_area)
    logger.debug("Loaded %d marine polygon parts from %s.", len(parts), _DATA_PATH.name)
    return tuple(parts)


def _parts() -> tuple[_Part, ...]:
    """The loaded polygons, reading the file the first time it is asked for.

    Not at import: the arq worker imports this package and never geocodes, and neither does
    most of the test suite. The cost is ~26 ms of JSON parsing and tuple building, once per
    process, spent synchronously inside whichever request happens to be first - including one
    served entirely from cache. That is accepted rather than overlooked: a single event per
    worker, well inside the deadline this endpoint already budgets for the provider, where
    moving it to a thread or to app startup would buy one request ~26 ms at the cost of wiring
    a lifespan hook into a module the worker does not use. Revisit it if the dataset ever
    grows by an order of magnitude.

    **Only a successful read is remembered.** Memoizing the failure would be cheaper and is
    the wrong trade: it turns one bad read into a fallback that is dead for the life of the
    process, recoverable only by restarting, on evidence no stronger than a single `OSError`.
    Nothing routine is expected to produce that - `scripts/build_marine_areas.py` stages its
    output and `os.replace`s it, so even a regeneration against the dev bind-mount is atomic
    - which is precisely why latching on one is the wrong response to it. The cost of
    retrying is a re-read and re-parse per lookup while the file stays broken, on a path
    already reached only after a provider miss, and `_load` reports the failure loudly once
    and at DEBUG thereafter rather than filling the log with it.
    """
    global _loaded
    if _loaded is None:
        _loaded = _load()
    return _loaded if _loaded is not None else ()


def _ring_contains(ring: Ring, longitude: float, latitude: float) -> bool:
    """Ray casting: count the ring's edges crossed by a ray running east from the point, and
    an odd count means inside.

    A point exactly on an edge is not decided consistently by this test - and does not need
    to be. This answers "which sea is this pin in" for a fallback, where a metre either side
    of a cartographer's line between two seas is not a distinction anyone is relying on.
    """
    inside = False
    previous_longitude, previous_latitude = ring[-1]
    for point_longitude, point_latitude in ring:
        if (point_latitude > latitude) != (previous_latitude > latitude):
            crossing = (previous_longitude - point_longitude) * (latitude - point_latitude) / (
                previous_latitude - point_latitude
            ) + point_longitude
            if longitude < crossing:
                inside = not inside
        previous_longitude, previous_latitude = point_longitude, point_latitude
    return inside


def _outer_contains(part: _Part, longitude: float, latitude: float) -> bool:
    """Inside the part's outline, islands not yet considered. The bounding box is checked
    first because it rejects almost everything for almost no work."""
    if not (part.min_lon <= longitude <= part.max_lon and part.min_lat <= latitude <= part.max_lat):
        return False
    return _ring_contains(part.rings[0], longitude, latitude)


def water_name(latitude: float, longitude: float) -> str | None:
    """The name of the water at a position - `None` for anywhere the dataset holds no water.

    Usually a sea or an ocean, but the dataset is wider than that and deliberately kept so:
    gulfs, straits, sounds, channels, fjords, a handful of estuarine rivers ("Amazon River"),
    a few named lakes ("Lake Pontchartrain") and two reefs, of which "Great Barrier Reef" is
    a far better answer for a pin there than "Coral Sea".

    It holds water, not coastlines, so "no polygon contains this" is the only thing it can
    say about a position - a point in the Sahara and a point in Lake Baikal, which is not in
    the file, are equally absent.

    **The first part whose outline contains the point decides, including deciding that the
    point is land.** Parts are ordered smallest-first, so that part is the most detailed
    description of the position the dataset holds, and its islands are the ones worth
    trusting. Falling through to the next candidate after a hole would answer with a coarser
    polygon that does not carry the same island - a rock in the Red Sea would come back
    "Indian Ocean" - which is the one wrong answer this can give that looks entirely
    plausible.
    """
    for part in _parts():
        if not _outer_contains(part, longitude, latitude):
            continue
        if any(_ring_contains(hole, longitude, latitude) for hole in part.rings[1:]):
            return None
        return part.name
    return None
