"""Name the sea at a position, from polygons vendored in the repo.

This exists because a pin in genuinely open water reverse-geocodes to nothing. Nominatim
does not consult sea polygons on `/reverse` at all - `27.0, 35.0` in the Red Sea and
`30.0, -40.0` in the mid-Atlantic both answer `{"error": "Unable to geocode"}`, at every
zoom level and with `layer=natural` - and open water is where a great deal of diving
happens. `services.geocoding_service` calls this only when the provider had nothing.

**Why a data file rather than a second provider.** Marine Regions' REST API answers the same
question, but adding it would mean a second outbound host, a second licence and a second
failure mode for a feature whose whole selling point is that it works out of the box. The
data is small, public domain, and does not change: 293 Natural Earth polygons, checked in.
That also matches what this project decided when it kept dive-site coordinates in two plain
`Float` columns rather than adding PostGIS - a self-hoster should not acquire an install
step for a coarse convenience.

**Why no geometry library.** Ray casting over ~350 polygon parts, behind a bounding-box
reject, is a few dozen lines and runs in well under a millisecond. `shapely` would pull GEOS
into the image to do the same arithmetic.

`data/marine_areas.geojson` is regenerated by `scripts/build_marine_areas.py`, which records
the source URL, the retrieval date and the licence inside the file itself.
"""

import json
import logging
from dataclasses import dataclass
from functools import cache
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "marine_areas.geojson"

Ring = tuple[tuple[float, float], ...]


@dataclass(frozen=True, slots=True)
class _Part:
    """One contiguous polygon, not one sea.

    Splitting per part rather than per feature is what keeps the antimeridian out of this
    module: the Bering Sea arrives from Natural Earth as two polygons, one either side of
    ±180, so each one is an ordinary lon/lat rectangle. It also sharpens the bounding box -
    a feature-level box for the Bering would span the entire globe and reject nothing.
    """

    name: str
    min_lon: float
    min_lat: float
    max_lon: float
    max_lat: float
    # Outer ring first, holes after. The holes are islands, and a diver standing on one is
    # not in the sea.
    rings: tuple[Ring, ...]

    @property
    def box_area(self) -> float:
        return (self.max_lon - self.min_lon) * (self.max_lat - self.min_lat)


def _ring(coordinates: list[Any]) -> Ring:
    return tuple((float(point[0]), float(point[1])) for point in coordinates)


def _parts_of(name: str, geometry: dict[str, Any]) -> list[_Part]:
    polygons = [geometry["coordinates"]] if geometry["type"] == "Polygon" else geometry["coordinates"]

    parts: list[_Part] = []
    for polygon in polygons:
        rings = tuple(_ring(ring) for ring in polygon)
        longitudes = [longitude for longitude, _ in rings[0]]
        latitudes = [latitude for _, latitude in rings[0]]
        parts.append(
            _Part(
                name=name,
                min_lon=min(longitudes),
                min_lat=min(latitudes),
                max_lon=max(longitudes),
                max_lat=max(latitudes),
                rings=rings,
            )
        )
    return parts


@cache
def _parts() -> tuple[_Part, ...]:
    """Every polygon part, **smallest bounding box first**, so the first hit wins.

    Overlap is the norm rather than the exception in this dataset - a point in the Red Sea
    is also inside "Indian Ocean", and one in the Coral Sea is inside "South Pacific Ocean".
    The smaller polygon is always the more useful answer to "where is this dive", so sorting
    once at load turns "smallest match wins" into "return on the first match" and removes the
    need to test the rest.

    Comparing *bounding box* area rather than true polygon area is deliberate: it needs no
    geometry library and is not a close call for any pair this has to separate.

    Loaded on first use, not at import: the arq worker imports this package and never
    geocodes, and neither does most of the test suite. The cost is ~30 ms of JSON parsing and
    tuple building, once per process, and it is spent synchronously inside whichever request
    happens to be first - including one served entirely from cache. That is accepted rather
    than overlooked: it is a single event per worker, well inside the deadline this endpoint
    already budgets for the provider, and moving it to a thread or to app startup would buy
    one request ~30 ms at the cost of wiring a lifespan hook into a module the worker does
    not use. Revisit it if the dataset ever grows by an order of magnitude.
    """
    document = json.loads(_DATA_PATH.read_text(encoding="utf-8"))

    parts: list[_Part] = []
    for feature in document["features"]:
        parts.extend(_parts_of(feature["properties"]["name"], feature["geometry"]))

    parts.sort(key=lambda part: part.box_area)
    logger.debug("Loaded %d marine polygon parts from %s.", len(parts), _DATA_PATH.name)
    return tuple(parts)


def _ring_contains(ring: Ring, longitude: float, latitude: float) -> bool:
    """Ray casting: count the ring's edges crossed by a ray running east from the point, and
    an odd count means inside.

    A point exactly on an edge is not decided consistently by this test - and does not need
    to be. This answers "which sea is this pin in" for a fallback, where a metre either side
    of a cartographer's line between two seas is not a distinction anyone is relying on.
    """
    inside = False
    previous_longitude, previous_latitude = ring[-1]
    for point_longitude, point_latitude in ring:
        if (point_latitude > latitude) != (previous_latitude > latitude):
            crossing = (previous_longitude - point_longitude) * (latitude - point_latitude) / (
                previous_latitude - point_latitude
            ) + point_longitude
            if longitude < crossing:
                inside = not inside
        previous_longitude, previous_latitude = point_longitude, point_latitude
    return inside


def _part_contains(part: _Part, longitude: float, latitude: float) -> bool:
    if not (part.min_lon <= longitude <= part.max_lon and part.min_lat <= latitude <= part.max_lat):
        return False
    if not _ring_contains(part.rings[0], longitude, latitude):
        return False
    return not any(_ring_contains(hole, longitude, latitude) for hole in part.rings[1:])


def sea_name(latitude: float, longitude: float) -> str | None:
    """The name of the sea, ocean, gulf or strait at a position - `None` over land.

    "Over land" here means "outside every marine polygon", which is the only thing this can
    know: the dataset holds water, not coastlines, so a point in the Sahara and a point in
    Lake Baikal are both simply absent from it.
    """
    for part in _parts():
        if _part_contains(part, longitude, latitude):
            return part.name
    return None
